Repository umutsefkansak/file-analyzer, pull requests merged in 2025-07, with the labels that each got.

#4 Refactor: Extract interfaces for existing service classes
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/ArchiveService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/FileProcessingService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/abstracts/IArchvieService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/abstracts/IFileProcessingService.java
Labels: refactor

#6 feat: implement ThreadManagementService and enhance FileProcessingService
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/FileProcessingService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/ThreadManagementService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/abstracts/IThreadManagementService.java
  output/archived-files.zip
Labels: feat, refactor

#8 feat: implement global exception handling
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/dto/ErrorResponse.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/GlobalExceptionHandler.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/archive/ArchiveCreationException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/archive/ArchiveExtractionException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/archive/InvalidArchiveException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/directory/DirectoryAccessException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/directory/DirectoryNotFoundException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/file/FileAnalyzerException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/file/FileNotFoundException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/file/FileProcessingException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/file/InvalidFileTypeException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/thread/ThreadExecutionException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/exception/thread/ThreadInterruptedException.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/ArchiveService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/FileAnalysisService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/FileProcessingService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/ThreadManagementService.java
Labels: feat, style, refactor

#10 Feature/file upload service
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/controller/FileAnalysisController.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/FileUploadService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/abstracts/IFileUploadService.java
  backend/fileanalyzer/src/main/resources/application.properties
  output/archive_20250718_214856.zip
  output/archive_20250719_000729.zip
  output/archive_20250719_002755.zip
  output/archive_20250719_003842.zip
  output/archive_20250719_004050.zip
  output/archive_20250719_004156.zip
  output/archive_20250719_004329.zip
  output/archive_20250719_004354.zip
Labels: feat

#12 Implement initial frontend, add file download endpoint and example files
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/controller/FileAnalysisController.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/FileDownloadService.java
  backend/fileanalyzer/src/main/java/com/infina/fileanalyzer/service/abstracts/IFileDownloadService.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.js
  frontend/src/components/FileAnalyzerApp.js
  frontend/src/styles/FileAnalyzer.css
  input/text1.txt
  input/text2.txt
  input/text3.txt
  output/archive_20250718_214856.zip
  output/archive_20250719_000729.zip
  output/archive_20250719_002755.zip
  output/archive_20250719_003842.zip
  output/archive_20250719_004050.zip
  output/archive_20250719_004156.zip
  output/archive_20250719_004329.zip
  output/archive_20250719_004354.zip
  output/archive_20250720_175648.zip
  output/archived-files.zip
Labels: enhancement, feat

#15 style: updated button with a new style variant
  frontend/src/components/FileAnalyzerApp.js
Labels: style
